version: '3.7'
services:
        mysql_db:
                image: mysql:latest
                container_name: mysql_container
                restart: always
                environment:
                         MYSQL_USER: messager
                         MYSQL_ROOT_PASSWORD: messager 
                         MYSQL_PASSWORD: messager
                         MYSQL_DATABASE: messager
                ports:
                        - 3306:3306
   
        authentication:
                container_name: authentication
                build:
                        context: $root/authentication/authentication
                        dockerfile: $root/authentication/authentication/Dockerfile
                command: mvn clean install -Dskiptest
                environment:
                        - spring.datasource.url=jdbc:mysql://${mysqlIp}:3306/messager
                        - spring.datasource.username=messager
                        - spring.datasource.password=messager
                restart: on-failure
                ports:
                        - "8080:8080"
                depends_on:
                        - mysql_db
                deploy:
                        mode: replicated
                        replicas: 1
   
        server:
                container_name: server
                build:
                        context: $root/socket-server
                        dockerfile: $root/socket-server/Dockerfile
                ports:
                        - "8000:8000"


           
