apiVersion: apps/v1
kind: Deployment
metadata:
 name: socket-server-deployment
spec:
 replicas: 1
 selector:
  matchLabels:
   app: socket-server
 template:
  metadata:
   labels:
    app: socket-server
  spec:
   containers:
    - name: socket-server
      image: 10.105.68.53:5000/socket-server:latest
      imagePullPolicy: "IfNotPresent"
      ports:
       - containerPort: 8000
      env:
       - name: DB_HOST
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: mysql-host
       - name: DB_NAME
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: mysql-dbName
       - name: DB_USERNAME
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: mysql-user
       - name: DB_PASSWORD
         valueFrom:
          secretKeyRef:
           name: mysql-secret
           key: mysql-password
